LLOGUER_DEFAULT_API_URL = "https://analisi.transparenciacatalunya.cat/resource/qww9-bvhh.json"
LLOGUER_DEFAULT_REQUEST_LIMIT = 1000
LLOGUER_DEFAULT_REQUEST_DELAY_SECONDS = 0.5
LLOGUER_DEFAULT_TIMEOUT_SECONDS = 30